version: "3.3"
services:

  web:
    build: ./E7_11
    command: python ./manage.py runserver 0.0.0.0:8008
    ports:
      - 8008:8008
    volumes:
      - ./E7_11:/data
    depends_on:
      - mongo
      - cache
    environment:
      HOST_DB: mongo
      USER_DB: admin
      PASS_DB: Passw0rd1
      CACHE_LOC: redis://cache:6379/1

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: mBase
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Passw0rd1
    volumes:
      - ./mongo_db:/data/db

  cache:
    image: redis
    ports:
      - 6379:6379